# Generated by Django 3.0.6 on 2020-10-22 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('custFirstName', models.CharField(max_length=100)),
                ('custLastName', models.CharField(max_length=100)),
                ('custEmail', models.CharField(max_length=50)),
                ('custMobileNo', models.BigIntegerField()),
                ('custCity', models.TextField(max_length=30)),
                ('custPassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('menuName', models.CharField(max_length=100)),
                ('menuType', models.CharField(max_length=100)),
                ('menuPrice', models.IntegerField()),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('bookingDtTime', models.DateTimeField()),
                ('tableNo', models.IntegerField()),
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BATable.Customer')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('restName', models.CharField(max_length=100)),
                ('restType', models.CharField(max_length=10)),
                ('restOwnerName', models.CharField(max_length=100)),
                ('restEmail', models.CharField(max_length=100)),
                ('restMobileNo1', models.BigIntegerField()),
                ('restLandLineNo', models.BigIntegerField()),
                ('restAddress', models.TextField(max_length=200)),
                ('restImg', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trnId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('trnDtTime', models.DateTimeField(auto_now=True)),
                ('total', models.BigIntegerField()),
                ('gst', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('netTotal', models.IntegerField()),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BATable.Orders')),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='restId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BATable.Restaurant'),
        ),
        migrations.CreateModel(
            name='ordermenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BATable.Customer')),
                ('menuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BATable.Menu')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BATable.Orders')),
            ],
            options={
                'db_table': 'ordermenu',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='restId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BATable.Restaurant'),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('feedbackId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('feedbackType', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=500)),
                ('restId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BATable.Restaurant')),
            ],
            options={
                'db_table': 'FeedBack',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('couponId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BATable.Customer')),
                ('menuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BATable.Menu')),
            ],
            options={
                'db_table': 'Coupon',
            },
        ),
    ]
