# Generated by Django 3.0.6 on 2020-10-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('custFirstName', models.CharField(max_length=100)),
                ('custLastName', models.CharField(max_length=100)),
                ('custEmail', models.CharField(max_length=50)),
                ('cutMobileNo', models.IntegerField(max_length=12)),
                ('custCity', models.TextField(max_length=30)),
                ('custPassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('restName', models.CharField(max_length=100)),
                ('restType', models.CharField(max_length=10)),
                ('restOwnerName', models.CharField(max_length=100)),
                ('restEmail', models.CharField(max_length=100)),
                ('restMobileNo1', models.IntegerField(max_length=12)),
                ('restLandLineNo', models.IntegerField(max_length=12)),
                ('restAddress', models.TextField(max_length=200)),
                ('restImg', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('menuName', models.CharField(max_length=100)),
                ('menuType', models.CharField(max_length=100)),
                ('menuPrice', models.IntegerField(max_length=50)),
                ('restId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BATable.Restaurant')),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
    ]
