# Generated by Django 3.0.6 on 2020-08-18 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobileNo', models.IntegerField()),
                ('city', models.TextField()),
                ('birthDate', models.DateField()),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('RestId', models.IntegerField(primary_key=True, serialize=False)),
                ('RestName', models.CharField(max_length=100)),
                ('OwnerName', models.CharField(max_length=100)),
                ('RestEmail', models.CharField(max_length=100)),
                ('MobileNo1', models.IntegerField()),
                ('MobileNo2', models.IntegerField()),
                ('RestAddr', models.TextField(max_length=200)),
                ('RestImg', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
            options={
                'db_table': 'Restaurent',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('MenuId', models.IntegerField(primary_key=True, serialize=False)),
                ('MenuName', models.CharField(max_length=100)),
                ('MenuPrice', models.IntegerField()),
                ('RestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BATable.Restaurent')),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
    ]
