# Generated by Django 3.0.6 on 2020-10-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BATable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cutMobileNo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menuPrice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restLandLineNo',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restMobileNo1',
            field=models.BigIntegerField(),
        ),
    ]
